config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: %i[passwords registrations]
  root 'static_pages#home'

  get  'add_groups',    to: 'ldap_users#add'
  post 'add_groups',    to: 'ldap_users#add_groups'
  get  'copy_groups',   to: 'ldap_users#copy'
  post 'copy_groups',   to: 'ldap_users#copy_groups'
  get  'create_user',   to: 'ldap_users#new'
  post 'create_user',   to: 'ldap_users#create'
  get  'destroy_user',  to: 'ldap_users#delete'
  post 'destroy_user',  to: 'ldap_users#destroy'
  get  'remove_groups', to: 'ldap_users#remove'
  post 'remove_groups', to: 'ldap_users#remove_groups'
  get  'search_groups', to: 'ldap_users#search'
  post 'search_groups', to: 'ldap_users#search_result'
  get  'update_user',   to: 'ldap_users#edit'
  post 'update_user',   to: 'ldap_users#update'

  get  'add_users',     to: 'ldap_groups#add'
  post 'add_users',     to: 'ldap_groups#add_users'
  get  'create_group',  to: 'ldap_groups#new'
  post 'create_group',  to: 'ldap_groups#create'
  get  'destroy_group', to: 'ldap_groups#delete'
  post 'destroy_group', to: 'ldap_groups#destroy'
  get  'remove_users',  to: 'ldap_groups#remove'
  post 'remove_users',  to: 'ldap_groups#remove_users'

  get  'search',        to: 'ldap_searches#search'
  post 'search',        to: 'ldap_searches#search_result'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="container mb-5">
  <h3 class="main-heading text-center">Group Operations</h3>
  <div class="row text-center">
    <div class="list-group-item col-md-4">
      <%= link_to "Create a new group", create_group_path, class: 'lead text-info' %>
    </div>
    <div class="list-group-item col-md-4">
      <%= link_to "Add multiple users to a group", add_users_path, class: 'lead text-info' %>
    </div>
    <div class="list-group-item col-md-4">
      <%= link_to "Copy user groups", copy_groups_path, class: 'lead text-info' %>
    </div>
    <div class="list-group-item col-md-4">
        <%= link_to "Delete an existing group", destroy_group_path, class: 'lead text-info' %>
    </div>
    <div class="list-group-item col-md-4">
      <%= link_to "Remove multiple users from a group", remove_users_path, class: 'lead text-info' %>
    </div>
  </div>
  <h3 class="main-heading text-center">User Operations</h3>
  <div class="row text-center">
    <div class="list-group-item col-md-4">
      <%= link_to "Create a new user", create_user_path, class: 'lead text-info' %>
    </div>
    <div class="list-group-item col-md-4">
      <%= link_to "Add a user to multiple groups", add_groups_path, class: 'lead text-info' %>
    </div>
    <div class="list-group-item col-md-4">
      <%= link_to "Change user password", update_user_path, class: 'lead text-info' %>
    </div>
    <div class="list-group-item col-md-4">
      <%= link_to "Delete an existing user", destroy_user_path, class: 'lead text-info' %>
    </div>
    <div class="list-group-item col-md-4">
      <%= link_to "Remove a user from multiple groups", remove_groups_path, class: 'lead text-info' %>
    </div>
  </div>
  <h3 class="main-heading text-center">Search Operations</h3>
  <div class="row text-center">
    <div class="list-group-item col-md-6">
      <%= link_to "Search the directory for a group or user", search_path, class: 'lead text-info' %>
    </div>
    <div class="list-group-item col-md-6">
      <%= link_to "Search for all group memberships of a user", search_groups_path, class: 'lead text-info' %>
    </div>
  </div>
</div>